export const Expressions = {
  bq: /\\begin\{quotation\}/,
  claim: /\\begin\{claim\}/,
  corollary: /\\begin\{corollary\}/,
  definition: /\\begin\{definition\}/,
  lemma: /\\begin\{lemma\}/,
  proposition: /\\begin\{proposition\}/,
  axiom: /\\begin\{axiom\}/,
  remark: /\\begin\{remark\}/,
  note: /\\begin\{note\}/,
  exercise: /\\begin\{exercise\}/,
  question: /\\begin\{question\}/,
  endclaim: /\\end\{claim\}/,
  endcorollary: /\\end\{corollary\}/,
  enddefinition: /\\end\{definition\}/,
  endexample: /\\end\{example\}/,
  endlemma: /\\end\{lemma\}/,
  endproposition: /\\end\{proposition\}/,
  endaxiom: /\\end\{axiom\}/,
  endremark: /\\end\{remark\}/,
  endnote: /\\end\{note\}/,
  endexercise: /\\end\{exercise\}/,
  endquestion: /\\end\{question\}/,
  endproblem: /\\end\{problem\}/,
  endsolution: /\\end\{solution\}/,
  endtheorem: /\\end\{theorem\}/,
  eq: /\\end\{quotation\}/,
  example: /\\begin\{example\}/,
  problem: /\\begin\{problem\}/,
  proof: /\\begin\{proof\}/,
  qed: /\\end\{proof\}/,
  solution: /\\begin\{solution\}/,
  theorem: /\\begin\{theorem\}/
};

export const Functions = {
  bq: () => '<p class="quotation">',
  claim: () => '<h4>Claim</h4>',
  corollary: () => '<h4>Corollary</h4>',
  definition: () => '<h4>Definition</h4>',
  lemma: () => '<h4>Lemma</h4>',
  proposition: () => '<h4>Proposition</h4>',
  axiom: () => '<h4>Axiom</h4>',
  remark: () => '<h4>Remark</h4>',
  note: () => '<h4>Note</h4>',
  exercise: () => '<h4>Exercise</h4>',
  question: () => '<h4>Question</h4>',
  endclaim: () => '',
  endcorollary: () => '',
  enddefinition: () => '',
  endexample: () => '',
  endlemma: () => '',
  endproposition: () => '',
  endaxiom: () => '',
  endremark: () => '',
  endnote: () => '',
  endexercise: () => '',
  endquestion: () => '',
  endproblem: () => '',
  endsolution: () => '',
  endtheorem: () => '',
  eq: () => '</p>',
  example: () => '<h4>Example</h4>',
  problem: () => '<h4>Problem</h4>',
  proof: () => '<h4>Proof</h4>',
  // amsthm closes a proof with an open square. Emitted as a character rather
  // than as math: MathJax defines no \qed, so the previous `$\qed$` surfaced
  // an "Undefined control sequence" box at the end of every proof.
  qed: () => '<span class="qed">□</span>',
  solution: () => '<h4>Solution</h4>',
  theorem: () => '<h4>Theorem</h4>'
};

export default {
  Expressions,
  Functions
};
